### ISSUE TITLE
Cannot parse keys from audio adaptationset

### ISSUE THREAD

**Issue by lwerdna** [iWas-Coder/web-dl#8]
Shows up as:

```
Traceback (most recent call last):
  File "/path/to/Downloads/web-dl/./web-dl.py", line 49, in <module>
    main()
  File "/path/to/Downloads/web-dl/./web-dl.py", line 35, in main
    video_keys, audio_keys = decryptor.extract_keys(args.url())
  File "/path/to/Downloads/web-dl/modules/decryptor.py", line 129, in extract_keys
    selected_adaptationset_audio_idx = adaptationsets_audio[0][0]
IndexError: list index out of range
```

since `adaptationsets_audio` is empty. The audio adaptationset element doesn't contain "lang" in my case, so the loop in `decrypt.py` passes over it and doesn't pick up the keys.

Here's the offending dash manifest: [stream.mpd.zip](https://github.com/iWas-Coder/web-dl/files/14379498/stream.mpd.zip)

**Comment by iWas-Coder** [comment]
Hello! Thanks for opening the issue, it's very much appreciated :)
Will work on it, all updates will be referenced in this thread.

**Comment by montvid** [comment]
Got the same error, how to fix it?

[*] AdaptationSet #0: (?)
[*] AdaptationSet #1: (audio, \x7f\x7f\x7f)
[*] AdaptationSet #2: (audio, Lithuanian)
Traceback (most recent call last):
  File "/home/kvb/web-dl/./web-dl.py", line 49, in <module>
    main()
  File "/home/kvb/web-dl/./web-dl.py", line 35, in main
    video_keys, audio_keys = decryptor.extract_keys(args.url())
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kvb/web-dl/modules/decryptor.py", line 122, in extract_keys
    selected_adaptationset_video_idx = adaptationsets_video[0][0]
                                       ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by iWas-Coder** [comment]
Hello, thanks for commenting on the issue! From what I remember, there are some fields in the manifest which greatly vary between instances, and I couldn't find any common specification on how the structure should be for these kinds of media.

If you're able to attach the manifest file, it'll help a lot to adapt the implementation and try to make it more robust.

I'm currenly working actively on some other projects, but eventually I'll come back to this one and try to resolve all posted issues.

Thanks again for the contribution and for your interest, it's very much appretiated! :smile:
